# Generated by Django 3.2.18 on 2023-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_blog', '0002_article_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
